### ISSUE TITLE
Remove appindicator dependency

### ISSUE THREAD

**Issue by pedronveloso** [sgricci/dewdrop#21] opened 2014-01-09 14:33 UTC
``` bash
./dewdrop                    
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./dewdrop/__main__.py", line 3, in <module>
  File "./dewdrop/app.py", line 8, in <module>
  File "./dewdrop/dewdrop.py", line 18, in <module>
ImportError: No module named appindicator
```

Some of us don't use Ubuntu, and Unity is only used by Ubuntu users. Please remove this dependency.

**Comment by sgricci** [comment] 2014-01-09 15:58
This is a duplicate of #20.

Also, AppIndicator is not Unity, or Ubuntu.  It's a library created by Canonical, but not exclusive to it.

Just created a beta which has a fix for this, feel free to try it here: http://d.pr/f/LMD4 If not, it'll be in the next release.

**Closed as completed by sgricci** 2014-01-09 15:58 UTC
